import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {NextFontWithVariable} from "@next/font";
import Provider from "@/app/Provider";


const gtSuper:NextFontWithVariable = localFont({
    src: "./fonts/gtsuper.woff",
    variable: "--font-gtsuper",
    weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>):JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${gtSuper.variable} ${gtSuper.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
